Repository OpenChemistry/avogadroapp, pull requests merged in 2025-06, with the labels that each got.

#567 Windows Qt6 build is failing due to std::chrono issue
  thirdparty/3DConnexion/inc/SpaceMouse/CCookieCollection.hpp
Labels: build

#568 Ensure the display type list is sorted
  avogadro/mainwindow.cpp
Labels: bug

#543 Synchronize workflows
  .github/workflows/add_artifact_urls.yml
  .github/workflows/build_cmake.yml
  .github/workflows/build_flatpak.yml
  .github/workflows/build_linux.yml
  .github/workflows/build_m1.yml
  .github/workflows/build_qt6.yml
  .github/workflows/build_windows.yml
Labels: build

#576 When multiple files are dropped, make sure to queue them for reading
  avogadro/mainwindow.cpp
Labels: bug, crash

#583 Fix bug with fog not starting with the correct background color
  avogadro/mainwindow.cpp
Labels: bug
